In [30]:
b = 32
w1 = 1.8

X1 = 100

y_pred = 1 * b + X1 * w1
print(y_pred)

212.0


In [5]:
import torch

b = torch.tensor(32)
w1 = torch.tensor(1.8)

X1 = torch.tensor([10, 38, 100, 150])
# X1 = torch.tensor([100]) # X1 can be single value also

y_pred = 1 * b + X1 * w1
# Explanation:  1*32 + [10, 38, 100, 150]*1.8 = 32+ [18, 68.4, 180, 270] = [50, 100.4, 212, 302]

print("\n Prediction y_pred : ", y_pred)
print(y_pred[1].item())

print(b.shape)
print(X1.shape)
print(b.size())
print(X1.size())


 Prediction y_pred :  tensor([ 50.0000, 100.4000, 212.0000, 302.0000])
100.4000015258789
torch.Size([])
torch.Size([4])
torch.Size([])
torch.Size([4])


In PyTorch, .size() and .shape are essentially the same.

In NumPy, .shape returns the dimensions, and .size (without parentheses) returns the total number of elements.

tensor(2.53) -> Zero-order tensor -> Scalar

tensor([2.53]) -> First-order tensor -> Vector

In [14]:
# Matrix in a Tensor
import torch

X = torch.tensor([
    [10],
    [38],
    [100],
    [150]
])

print(X)
print(X.shape)
print(X.size())
print(X.size(0)) # size in the 1st dimension

tensor([[ 10],
        [ 38],
        [100],
        [150]])
torch.Size([4, 1])
torch.Size([4, 1])
4


In [17]:
print(X[0])     # Print 0th row
print(X[0, 0])  # Print 0th row 0th value
print(X[1])     # Print 1st row
print(X[1, 0])  # Print 1st row 0th value
print(X[2])     # Print 2nd row
print(X[2, 0])  # Print 2nd row 0th value
print("=================")
print(X[2, :])  # In 2nd row, All elements
print(X[:, 0])  # All rows, only 1st element

tensor([10])
tensor(10)
tensor([38])
tensor(38)
tensor([100])
tensor(100)
tensor([100])
tensor([ 10,  38, 100, 150])


In [22]:
# Linear Neuron

import torch
from torch import nn

X = torch.tensor([
    [10.0],
    [38.0],
    [100.0],
    [150.0]
])

model = nn.Linear(1, 1)

print(model)
print("Default bias: ", model.bias)      # Will vary everytime
print("Default weight: ", model.weight)  # Will vary everytime

y_pred = model(X)
print(y_pred)

Linear(in_features=1, out_features=1, bias=True)
Default bias:  Parameter containing:
tensor([0.0871], requires_grad=True)
Default weight:  Parameter containing:
tensor([[0.8502]], requires_grad=True)
tensor([[  8.5894],
        [ 32.3959],
        [ 85.1102],
        [127.6217]], grad_fn=<AddmmBackward0>)


In [23]:
model.bias = nn.Parameter(
    torch.tensor([32.0])
)
model.weight = nn.Parameter(
    torch.tensor([[1.8]])
)

print(model.bias)
print(model.weight)

y_pred = model(X)
print(y_pred)

Parameter containing:
tensor([32.], requires_grad=True)
Parameter containing:
tensor([[1.8000]], requires_grad=True)
tensor([[ 50.0000],
        [100.4000],
        [212.0000],
        [302.0000]], grad_fn=<AddmmBackward0>)


In [26]:
import torch
from torch import nn

X = torch.tensor([
    [10],
    [38],
    [100],
    [150]
], dtype=torch.float32)

X = X.type(torch.int64)
print(X)
print(X.dtype)
print("============")
result = X * 0.5
print(result)
print(result.dtype)

tensor([[ 10],
        [ 38],
        [100],
        [150]])
torch.int64
tensor([[ 5.],
        [19.],
        [50.],
        [75.]])
torch.float32


In [29]:
import torch
from torch import nn

X = torch.tensor([
    [10],
    [38],
    [100],
    [150]
], dtype=torch.float32)

model = nn.Linear(1, 1)

# model.bias = nn.Parameter(torch.tensor([32]))  # This will fail so add float32
model.bias = nn.Parameter(
    torch.tensor([32], dtype=torch.float32)
)
model.weight = nn.Parameter(
    torch.tensor([[1.8]], dtype=torch.float32)
)

print(model.bias)
print(model.weight)

y_pred = model(X)
print(y_pred)

Parameter containing:
tensor([32.], requires_grad=True)
Parameter containing:
tensor([[1.8000]], requires_grad=True)
tensor([[ 50.0000],
        [100.4000],
        [212.0000],
        [302.0000]], grad_fn=<AddmmBackward0>)
