In [1]:
import torch
from torch import nn

# Input: Temperature in °C
X1 = torch.tensor([[10]], dtype=torch.float32)
# Actual value: Temperature °F
y1 = torch.tensor([[50]], dtype=torch.float32)

# Input: Temperature in °C
X2 = torch.tensor([[37.78]], dtype=torch.float32)
# Actual value: Temperature °F
y2 = torch.tensor([[100.0]], dtype=torch.float32)

### 1st training

In [2]:
model = nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

print("\n======Before training======\n")
print(model.bias)
print(model.weight)
print(model.parameters)
# Training pass
optimizer.zero_grad()
outputs = model(X1)
loss = loss_fn(outputs, y1)
loss.backward()
optimizer.step()

print("\n======After training======\n")
print(model.bias)
print(model.weight)
print(model.parameters)

print("\n\nPrediction")
y1_pred = model(X1)
print("y1_pred =", y1_pred)


======Before training======

Parameter containing:
tensor([0.0222], requires_grad=True)
Parameter containing:
tensor([[-0.6234]], requires_grad=True)
<bound method Module.parameters of Linear(in_features=1, out_features=1, bias=True)>

======After training======

Parameter containing:
tensor([0.1346], requires_grad=True)
Parameter containing:
tensor([[0.5008]], requires_grad=True)
<bound method Module.parameters of Linear(in_features=1, out_features=1, bias=True)>


Prediction
y1_pred = tensor([[5.1429]], grad_fn=<AddmmBackward0>)


### 2nd training

In [3]:
model = nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001) # If you're getting prediction as nan. Then decrease the learning rate more..

for i in range(0, 100000): # change from 10000 -> 50000 -> 100000 to see the prediction difference
    # Training pass
    optimizer.zero_grad()
    outputs = model(X1)
    loss = loss_fn(outputs, y1)
    loss.backward()
    optimizer.step()

    optimizer.zero_grad()
    outputs = model(X2)
    loss = loss_fn(outputs, y2)
    loss.backward()
    optimizer.step()

    if i % 100 == 0:
        print(model.bias)
        print(model.weight)

y1_pred = model(X1)
print("y1_pred =", y1_pred)

Parameter containing:
tensor([0.9988], requires_grad=True)
Parameter containing:
tensor([[0.4690]], requires_grad=True)
Parameter containing:
tensor([1.3863], requires_grad=True)
Parameter containing:
tensor([[2.7177]], requires_grad=True)
Parameter containing:
tensor([1.6997], requires_grad=True)
Parameter containing:
tensor([[2.7083]], requires_grad=True)
Parameter containing:
tensor([2.0099], requires_grad=True)
Parameter containing:
tensor([[2.6990]], requires_grad=True)
Parameter containing:
tensor([2.3169], requires_grad=True)
Parameter containing:
tensor([[2.6898]], requires_grad=True)
Parameter containing:
tensor([2.6208], requires_grad=True)
Parameter containing:
tensor([[2.6807]], requires_grad=True)
Parameter containing:
tensor([2.9216], requires_grad=True)
Parameter containing:
tensor([[2.6717]], requires_grad=True)
Parameter containing:
tensor([3.2192], requires_grad=True)
Parameter containing:
tensor([[2.6628]], requires_grad=True)
Parameter containing:
tensor([3.5139], r

In [4]:
import torch
from torch import nn

X1 = torch.tensor([[10.0]]) # Input: Temperature in °C
y1 = torch.tensor([[50.0]]) # Actual value: Temperature °F

X2 = torch.tensor([[37.78]]) # Input: Temperature in °C
y2 = torch.tensor([[100.0]]) # Actual value: Temperature °F

model = nn.Linear(1, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)
loss_fn = torch.nn.MSELoss()

for i in range(0, 50000):
    optimizer.zero_grad()
    outputs = model(X1)
    loss = loss_fn(outputs, y1)
    loss.backward()
    optimizer.step()

    optimizer.zero_grad()
    outputs = model(X2)
    loss = loss_fn(outputs, y2)
    loss.backward()
    optimizer.step()
    if i % 100 == 0:
        print(model.weight)
        print(model.bias)

Parameter containing:
tensor([[0.5022]], requires_grad=True)
Parameter containing:
tensor([-0.6397], requires_grad=True)
Parameter containing:
tensor([[2.7663]], requires_grad=True)
Parameter containing:
tensor([-0.2349], requires_grad=True)
Parameter containing:
tensor([[2.7565]], requires_grad=True)
Parameter containing:
tensor([0.0951], requires_grad=True)
Parameter containing:
tensor([[2.7467]], requires_grad=True)
Parameter containing:
tensor([0.4217], requires_grad=True)
Parameter containing:
tensor([[2.7370]], requires_grad=True)
Parameter containing:
tensor([0.7449], requires_grad=True)
Parameter containing:
tensor([[2.7274]], requires_grad=True)
Parameter containing:
tensor([1.0649], requires_grad=True)
Parameter containing:
tensor([[2.7179]], requires_grad=True)
Parameter containing:
tensor([1.3816], requires_grad=True)
Parameter containing:
tensor([[2.7085]], requires_grad=True)
Parameter containing:
tensor([1.6950], requires_grad=True)
Parameter containing:
tensor([[2.6992]

### Batch learning

In [5]:
import torch
from torch import nn

# Input: Temperature in °C
X = torch.tensor([
    [10],
    [37.78]
], dtype=torch.float32)

# Actual value: Temperature °F
y = torch.tensor([
    [50],
    [100.0]
], dtype=torch.float32)

In [6]:
model = nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)

for i in range(0, 150000):
    # Training pass
    optimizer.zero_grad()
    outputs = model(X)
    loss = loss_fn(outputs, y)
    loss.backward()
    optimizer.step()

    if i % 100 == 0:
        print(model.bias)
        print(model.weight)

print("----")

measurements = torch.tensor([
    [37.5]
], dtype=torch.float32)

model.eval()
with torch.no_grad():
    prediction = model(measurements)
    print(prediction)

Streaming output truncated to the last 5000 lines.
Parameter containing:
tensor([[2.0767]], requires_grad=True)
Parameter containing:
tensor([23.1995], requires_grad=True)
Parameter containing:
tensor([[2.0753]], requires_grad=True)
Parameter containing:
tensor([23.2438], requires_grad=True)
Parameter containing:
tensor([[2.0739]], requires_grad=True)
Parameter containing:
tensor([23.2879], requires_grad=True)
Parameter containing:
tensor([[2.0725]], requires_grad=True)
Parameter containing:
tensor([23.3318], requires_grad=True)
Parameter containing:
tensor([[2.0712]], requires_grad=True)
Parameter containing:
tensor([23.3754], requires_grad=True)
Parameter containing:
tensor([[2.0698]], requires_grad=True)
Parameter containing:
tensor([23.4188], requires_grad=True)
Parameter containing:
tensor([[2.0684]], requires_grad=True)
Parameter containing:
tensor([23.4621], requires_grad=True)
Parameter containing:
tensor([[2.0671]], requires_grad=True)
Parameter containing:
tensor([23.5051], r

37.5 Celcius is approximately 99.4993(~100) Fahrenheit